### ISSUE TITLE
Error when running checker

### ISSUE THREAD

**Issue by robert-zoro** [g3th/Nordvpn-Account-Checker#1]
![snap](https://github.com/g3th/Nordvpn-Account-Checker/assets/143828658/e348ebf9-eea5-4deb-bf1b-a55d2a9e32a6)

Hi! When I run the checker I get this error. What should I do to fix it?
Thank you!

**Comment by g3th** [comment]
The error seems to indicate something wrong with the path where Chromium is stored (i.e. it's inexistent). 

There is no line 55 in the current version of [options.py](https://github.com/SeleniumHQ/selenium/blob/trunk/py/selenium/webdriver/chromium/options.py), but line 53 raises a "Binary location error" because 'self.binary_location' is expecting a string. So it seems on your system there is no path for Chromium.

I have fixed some path errors regarding Windows/Linux, I would suggest checking your chromedriver version, your selenium version and checking that Chromium is installed correctly.

I could not reproduce this error on my bare-metal kali system, as everything works correctly.

**Comment by groozaop** [comment]
Getting same error while trying it on colab..  any fix ?

**Comment by g3th** [comment]
> Getting same error while trying it on colab.. any fix ?

I am not sure what 'colab' refers to. Do you mean "Google Colab?" 

Google Colab allows you to execute Python (or other language) code in-browser. Colab will not work directly with selenium webdriver. Please browse:

https://github.com/googlecolab/colabtools/issues/3347

Please refer to the post above regarding your error in a full-fledged operating system.
